export const RegisterLocators = {
  titleSignup: 'New User Signup!',
  nameInput: 'Name',
  emailInput: 'Email Address',
  signupConfirmBtn: 'Signup',
  messageAccountInformation: 'Enter Account Information', 
  chkFemale: 'Mrs.',
  passwordInput: 'Password *',
  dayBithIput: '#days',
  monthBirthInput: '#months',
  yearBirthInput: '#years',
  chkReceiveOffer: 'Receive special offers from',
  chkNewsLetter: 'Sign up for our newsletter',
  fistNameInput:'First name *',
  lastNameInput:'Last name *',
  companyInput: 'Company',
  addressInput: 'Address * (Street address, P.',
  stateInput: 'State *',
  cityInput: 'City * Zipcode *',
  zipCodeInput: '#zipcode',
  mobileNumberInput: 'Mobile Number *',
  btnCreateAccount: 'Create Account',
  messageAccountCreated: 'Account Created',
  btnContinue: 'Continue',
  messageAccountDeleted: 'Account Deleted'
};
